### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by Ryoga-exe** [Ryoga-exe/ac-library-zig#4]
## Data Structures
- [x] [fenwicktree](https://atcoder.github.io/ac-library/master/document_en/fenwicktree.html)
- [x] [segtree](https://atcoder.github.io/ac-library/master/document_en/segtree.html)
- [ ] [lazysegtree](https://atcoder.github.io/ac-library/master/document_en/lazysegtree.html)
- [ ] [string](https://atcoder.github.io/ac-library/master/document_en/string.html)

## Math
- [ ] [math](https://atcoder.github.io/ac-library/master/document_en/math.html)
- [ ] [convolution](https://atcoder.github.io/ac-library/master/document_en/convolution.html)
- [ ] [modint](https://atcoder.github.io/ac-library/master/document_en/modint.html)

## Graphs
- [x] [dsu](https://atcoder.github.io/ac-library/master/document_en/dsu.html)
- [ ] [maxflow](https://atcoder.github.io/ac-library/master/document_en/maxflow.html)
- [ ] [mincostflow](https://atcoder.github.io/ac-library/master/document_en/mincostflow.html)
- [x] [scc](https://atcoder.github.io/ac-library/master/document_en/scc.html)
- [ ] [twosat](https://atcoder.github.io/ac-library/master/document_en/twosat.html)

- [ ] Documents
